# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://coffeescript.org/

$ ->
  #Show alert
  $('button[data-toggle="page-alert"]').click (e) ->
    e.preventDefault()
    id = $(this).attr('data-toggle-id')
    alert = $('#alert-' + id)
    timeOut = undefined
    alert.appendTo '.page-alerts'
    alert.slideDown()
    #Is autoclosing alert
    delay = $(this).attr('data-delay')
    if delay != undefined
      delay = parseInt(delay)
      clearTimeout timeOut
      timeOut = window.setTimeout((->
        alert.slideUp()
        return
      ), delay)
    return
  #Close alert
  $('.page-alert .close').click (e) ->
    e.preventDefault()
    $(this).closest('.page-alert').slideUp()
    return
  #Clear all
  $('.clear-page-alerts').click (e) ->
    e.preventDefault()
    $('.page-alert').slideUp()
    return
  return

# ---
# generated by js2coffee 2.0.4